package com.obisi.store;

import android.Manifest; import android.app.*; import android.content.*; import android.net.Uri; import android.os.*; import android.view.*; import android.widget.*; import androidx.appcompat.app.AppCompatActivity; import androidx.recyclerview.widget.*; import com.google.firebase.auth.FirebaseAuth; import com.google.firebase.firestore.*; import java.util.*;

public class MainActivity extends AppCompatActivity {
 FirebaseFirestore db; FirebaseAuth auth; ProductAdapter adapter; ArrayList<Product> products=new ArrayList<>();
 EditText search;
 @Override public void onCreate(Bundle b){super.onCreate(b); setContentView(R.layout.activity_main); db=FirebaseFirestore.getInstance(); auth=FirebaseAuth.getInstance();
  search=findViewById(R.id.search); RecyclerView rv=findViewById(R.id.list); rv.setLayoutManager(new LinearLayoutManager(this)); adapter=new ProductAdapter(products,this); rv.setAdapter(adapter); loadProducts();
  findViewById(R.id.whatsapp).setOnClickListener(v->{try{startActivity(new Intent(Intent.ACTION_VIEW, Uri.parse("https://wa.me/963967472881")));}catch(Exception e){}});
  findViewById(R.id.admin).setOnClickListener(v->adminLogin());
  search.addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int d){} public void onTextChanged(CharSequence s,int a,int b,int c){adapter.filter(s.toString());} public void afterTextChanged(android.text.Editable e){}});
  if(Build.VERSION.SDK_INT>=33) requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},44);
  com.google.firebase.messaging.FirebaseMessaging.getInstance().subscribeToTopic("obisi_all");
 }
 void loadProducts(){db.collection("products").whereEqualTo("active",true).orderBy("createdAt",Query.Direction.DESCENDING).addSnapshotListener((snap,e)->{if(e!=null)return; products.clear(); if(snap!=null) for(DocumentSnapshot d:snap.getDocuments()) products.add(Product.from(d)); adapter.setData(products);});}
 void adminLogin(){ final LinearLayout l=new LinearLayout(this); l.setOrientation(LinearLayout.VERTICAL); l.setPadding(30,10,30,10); EditText email=new EditText(this); email.setHint("إيميل الإدارة"); EditText pass=new EditText(this); pass.setHint("كلمة المرور"); pass.setInputType(0x81); l.addView(email); l.addView(pass); new AlertDialog.Builder(this).setTitle("دخول الإدارة").setView(l).setPositiveButton("دخول",(d,w)->auth.signInWithEmailAndPassword(email.getText().toString(),pass.getText().toString()).addOnSuccessListener(x->showAdmin())).setNegativeButton("إلغاء",null).show(); }
 void showAdmin(){ final String[] opts={"إضافة منتج","تسجيل خروج"}; new AlertDialog.Builder(this).setTitle("إدارة OBISI").setItems(opts,(d,i)->{if(i==0)addProduct();else auth.signOut();}).show(); }
 void addProduct(){ LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(25,5,25,5); EditText n=new EditText(this);n.setHint("اسم المنتج");EditText p=new EditText(this);p.setHint("السعر بالدولار");EditText c=new EditText(this);c.setHint("التصنيف");l.addView(n);l.addView(p);l.addView(c);new AlertDialog.Builder(this).setTitle("منتج جديد").setView(l).setPositiveButton("نشر",(d,w)->{HashMap<String,Object> m=new HashMap<>();m.put("name",n.getText().toString());m.put("price",p.getText().toString());m.put("category",c.getText().toString());m.put("active",true);m.put("isNew",true);m.put("createdAt",FieldValue.serverTimestamp());db.collection("products").add(m);}).setNegativeButton("إلغاء",null).show(); }
}
class Product {String id,name,price,category,imageUrl; static Product from(DocumentSnapshot d){Product p=new Product();p.id=d.getId();p.name=d.getString("name");p.price=d.getString("price");p.category=d.getString("category");p.imageUrl=d.getString("imageUrl");return p;}}
class ProductAdapter extends RecyclerView.Adapter<ProductAdapter.H> {ArrayList<Product> all,shown;Context c;ProductAdapter(ArrayList<Product>a,Context c){all=a;shown=new ArrayList<>(a);this.c=c;}void setData(ArrayList<Product>a){all=a;shown=new ArrayList<>(a);notifyDataSetChanged();}void filter(String q){shown.clear();for(Product p:all)if((p.name+" "+p.category).toLowerCase().contains(q.toLowerCase()))shown.add(p);notifyDataSetChanged();}public H onCreateViewHolder(android.view.ViewGroup p,int v){LinearLayout l=new LinearLayout(c);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(18,18,18,18);TextView n=new TextView(c);n.setTextSize(20);n.setId(1);TextView x=new TextView(c);x.setTextSize(16);x.setId(2);l.addView(n);l.addView(x);return new H(l);}public void onBindViewHolder(H h,int i){Product p=shown.get(i);h.n.setText(p.name==null?"":p.name);h.x.setText((p.category==null?"":p.category)+"  |  $"+(p.price==null?"":p.price));}public int getItemCount(){return shown.size();}static class H extends RecyclerView.ViewHolder{TextView n,x;H(View v){super(v);n=v.findViewById(1);x=v.findViewById(2);}}}
